package com.example.ui.goals

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.data.model.ChapterItem
import com.example.data.model.DailyGoalItem
import com.example.data.model.DailyStudyLog
import com.example.data.model.TestItem
import com.example.data.repository.JeeRepository
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.time.LocalDate
import java.time.temporal.ChronoUnit

data class DailyGoalsUiState(
    val selectedDate: LocalDate = LocalDate.now(),
    val goals: List<DailyGoalItem> = emptyList(),
    val studyLog: DailyStudyLog? = null,
    val upcomingTest: TestItem? = null,
    val isOneDayBeforeTest: Boolean = false,
    val chapters: List<ChapterItem> = emptyList()
)

@OptIn(ExperimentalCoroutinesApi::class)
class DailyGoalsViewModel(private val repository: JeeRepository) : ViewModel() {

    val selectedDate = MutableStateFlow(LocalDate.now())

    private val goalsFlow = selectedDate.flatMapLatest { date ->
        repository.getGoalsForDate(date.toString())
    }

    private val studyLogFlow = selectedDate.flatMapLatest { date ->
        repository.getStudyLogForDate(date.toString())
    }

    val uiState: StateFlow<DailyGoalsUiState> = combine(
        selectedDate,
        goalsFlow,
        studyLogFlow,
        repository.nextUpcomingTest,
        repository.allChapters
    ) { date, goals, log, test, chapters ->
        val isEve = if (test != null) {
            try {
                val parts = test.testDate.split("-")
                val monthMap = mapOf(
                    "Jan" to 1, "Feb" to 2, "Mar" to 3, "Apr" to 4, "May" to 5, "Jun" to 6,
                    "Jul" to 7, "Aug" to 8, "Sep" to 9, "Oct" to 10, "Nov" to 11, "Dec" to 12
                )
                val d = parts[0].toInt()
                val m = monthMap[parts[1]] ?: 10
                val y = parts[2].toInt()
                val testLocalDate = LocalDate.of(y, m, d)
                ChronoUnit.DAYS.between(date, testLocalDate) == 1L
            } catch (_: Exception) {
                false
            }
        } else false

        DailyGoalsUiState(
            selectedDate = date,
            goals = goals,
            studyLog = log,
            upcomingTest = test,
            isOneDayBeforeTest = isEve,
            chapters = chapters
        )
    }.stateIn(
        scope = viewModelScope,
        started = SharingStarted.WhileSubscribed(5000),
        initialValue = DailyGoalsUiState()
    )

    init {
        ensureGoalsForCurrentDate()
    }

    fun setDate(date: LocalDate) {
        selectedDate.value = date
        viewModelScope.launch {
            repository.generateDailyGoalsIfEmpty(date)
        }
    }

    fun previousDay() {
        setDate(selectedDate.value.minusDays(1))
    }

    fun nextDay() {
        setDate(selectedDate.value.plusDays(1))
    }

    fun goToToday() {
        setDate(LocalDate.now())
    }

    fun ensureGoalsForCurrentDate() {
        viewModelScope.launch {
            repository.generateDailyGoalsIfEmpty(selectedDate.value)
        }
    }

    fun regenerateGoals() {
        viewModelScope.launch {
            repository.generateDailyGoalsIfEmpty(selectedDate.value, forceRegenerate = true)
        }
    }

    fun toggleGoal(goal: DailyGoalItem) {
        viewModelScope.launch {
            repository.toggleGoalCompletion(goal)
        }
    }

    fun addCustomGoal(
        subject: String,
        subSubject: String,
        chapterId: Int,
        chapterName: String,
        taskType: String,
        title: String,
        description: String
    ) {
        viewModelScope.launch {
            val item = DailyGoalItem(
                dateString = selectedDate.value.toString(),
                subject = subject,
                subSubject = subSubject,
                chapterId = chapterId,
                chapterName = chapterName,
                taskType = taskType,
                title = title,
                description = description,
                isCompleted = false,
                isAutoGenerated = false
            )
            repository.addCustomGoal(item)
        }
    }

    fun deleteGoal(goal: DailyGoalItem) {
        viewModelScope.launch {
            repository.deleteGoal(goal.id)
        }
    }

    fun saveStudyLog(
        physicsHours: Float,
        chemHours: Float,
        mathHours: Float,
        questionsSolved: Int,
        notes: String
    ) {
        viewModelScope.launch {
            val log = DailyStudyLog(
                dateString = selectedDate.value.toString(),
                physicsHours = physicsHours,
                chemistryHours = chemHours,
                mathHours = mathHours,
                questionsSolved = questionsSolved,
                notes = notes
            )
            repository.saveStudyLog(log)
        }
    }

    class Factory(private val repository: JeeRepository) : ViewModelProvider.Factory {
        @Suppress("UNCHECKED_CAST")
        override fun <T : ViewModel> create(modelClass: Class<T>): T {
            return DailyGoalsViewModel(repository) as T
        }
    }
}
