package com.example.data.local

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.example.data.model.DailyGoalItem
import kotlinx.coroutines.flow.Flow

@Dao
interface DailyGoalDao {
    @Query("SELECT * FROM daily_goals WHERE dateString = :dateString ORDER BY isCompleted ASC, subject ASC")
    fun getGoalsForDate(dateString: String): Flow<List<DailyGoalItem>>

    @Query("SELECT * FROM daily_goals WHERE dateString = :dateString ORDER BY subject ASC")
    suspend fun getGoalsForDateSync(dateString: String): List<DailyGoalItem>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertGoals(goals: List<DailyGoalItem>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertGoal(goal: DailyGoalItem): Long

    @Update
    suspend fun updateGoal(goal: DailyGoalItem)

    @Query("DELETE FROM daily_goals WHERE id = :id")
    suspend fun deleteGoal(id: Int)

    @Query("DELETE FROM daily_goals WHERE dateString = :dateString AND isAutoGenerated = 1")
    suspend fun clearAutoGeneratedForDate(dateString: String)
}
