package com.example.data.model

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "daily_goals")
data class DailyGoalItem(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val dateString: String, // e.g. "2026-09-28"
    val subject: String,    // "PHYSICS", "CHEMISTRY", "MATHEMATICS"
    val subSubject: String, // "PHYSICS", "P_CHEM", "I_CHEM", "O_CHEM", "MATH"
    val chapterId: Int,
    val chapterName: String,
    val taskType: String,   // "THEORY", "SHORT_NOTES", "MATHONGO_CBQ", "MODULE_EX2", "EKLAVYA", "PREV_TEST_REV", "CUSTOM"
    val title: String,
    val description: String,
    val targetCount: Int = 1,
    val completedCount: Int = 0,
    val weightageTag: String = "High Weightage", // "High Weightage", "Moderate", "Crucial"
    val targetQuestions: Int = 35,
    val solvedQuestions: Int = 20,
    val isFormulaRevised: Boolean = false,
    val isSummarySubmitted: Boolean = false,
    val isCompleted: Boolean = false,
    val isAutoGenerated: Boolean = true,
    val isTestEveRevision: Boolean = false,
    val timestamp: Long = System.currentTimeMillis()
)
